services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web1:
    build: ./web1/
    ports:
      - '81:5000'
  web2:
    build: ./web2/
    ports:
      - '82:5000'
  nginx:
    build: ./nginx/
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2
